### ISSUE TITLE
macOS: Lossless PNG encoding output much larger in input 

### ISSUE THREAD

**Issue by mgenware** [awxkee/jxl-coder-swift#2]
[A runnable app to test](https://github.com/mgenware/jxlCoderTest)

Encode code:
```swift
let data: Data = try? JXLCoder.encode(image: img, compressionOption: .loseless, quality: 100)
```
The resulting image is much larger than cjxl result:

```sh
# cjxl command
cjxl IMG_2473.PNG cjxl.jxl -d 0
```

<img width="838" alt="image" src="https://github.com/awxkee/jxl-coder-swift/assets/11565096/48813785-7a40-4aef-b3fa-6b9aefe2321a">

**Comment by awxkee** [comment]
> [A runnable app to test](https://github.com/mgenware/jxlCoderTest)
> 
> Encode code:
> 
> ```swift
> let data: Data = try? JXLCoder.encode(image: img, compressionOption: .loseless, quality: 100)
> ```
> 
> The resulting image is much larger than cjxl result:
> 
> ```shell
> # cjxl command
> cjxl IMG_2473.PNG cjxl.jxl -d 0
> ```
> 
> <img alt="image" width="838" src="https://user-images.githubusercontent.com/11565096/274536540-48813785-7a40-4aef-b3fa-6b9aefe2321a.png">

Hi,
I made some changes it should be in range now. However it will be always some difference due to redrawing round trip

**Comment by mgenware** [comment]
Thanks for the quick response. It works!
