### ISSUE TITLE
Method for wrapping libjxl in an XCFramework?

### ISSUE THREAD

**Issue by adamshin** [awxkee/jxl-coder-swift#4]
I’m trying to write a wrapper library for libjxl, similar to this one. I haven’t been able to figure out how to build libjxl for iOS and wrap it in an XCFramework. There isn’t much documentation on building the project for macOS/iOS.

How did you accomplish this?

**Comment by awxkee** [comment]
It is regular CMake project, isn't it?

You'll need a build command 

```
rm -rf working-dir
mkdir -p working-dir
cd working-dir

cmake .. \
      -G Ninja \
      -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake \
      -DBUILD_TESTING=OFF \
      -DPLATFORM=OS64 \
      -DDEPLOYMENT_TARGET=13 \
      -DCMAKE_CXX_COMPILER=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ \
      -DCMAKE_C_COMPILER=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang \
      -DJPEGXL_ENABLE_TOOLS=OFF -DJPEGXL_ENABLE_DEVTOOLS=0 -DJPEGXL_ENABLE_EXAMPLES=0 -DJPEGXL_ENABLE_DEVTOOLS=OFF -DJPEGXL_ENABLE_FUZZERS=OFF \
      -DHWY_ENABLE_TESTS=0 -DBROTLI_DISABLE_TESTS=0 \
      -DJPEGXL_ENABLE_SJPEG=0 \
      -DJPEGXL_STATIC=ON \
      -DJPEGXL_BUNDLE_LIBPNG=OFF \
      -DHWY_ENABLE_INSTALL=OFF -DHWY_ENABLE_EXAMPLES=OFF -DHWY_ENABLE_TESTS=OFF \
      -DBROTLI_BUNDLED_MODE=ON \
      -DJPEGXL_ENABLE_JPEGLI=YES \
      -DENABLE_JPEGLI_DEFAULT=YES \
      -DJPEGXL_ENABLE_JPEGLI_LIBJPEG=OFF \
      -DCMAKE_BUILD_TYPE=Release

ninja

```
And toolchain you may download from [here](https://github.com/leetal/ios-cmake) or write your own.

I prefer build with ninja however if you prefer other build tool just change ninja to it.

After you build static library you'll need to create framework. If you wish to create a FAT static library before ( this is indeed required if you will build not only for iOS Simulator x86 SDK but for arm64 also or same to Mac ) you have to build for each platform and create fat libraries by command 

`lipo -create arm_library_simulator.a  intel_library_simulator.a any_other_platform_library_simulator.a -output fat_library.a`

And then merge to framework.

```
xcodebuild -create-xcframework \
        -library fat_library.a -headers library_headers \
        -library ios_library.a -headers library_headers \
        etc..,.
        -output frameworks/$i.xcframework
```
